// web/caclouky-web/src/app/features/admin/admin-dashboard/admin-dashboard.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTableModule } from '@angular/material/table';
import { MatChipsModule } from '@angular/material/chips';
import { CheckoutsService, Checkout } from '../../../core/services/checkouts.service';
import { ReservationsService, Reservation } from '../../../core/services/reservations.service';

@Component({
  selector: 'app-admin-dashboard',
  standalone: true,
  imports: [
    CommonModule, RouterLink,
    MatCardModule, MatButtonModule, MatIconModule,
    MatTableModule, MatChipsModule
  ],
  template: `
    <div class="dashboard">
      <h2>Dashboard</h2>

      <!-- Stat cards -->
      <div class="stats-row">
        <mat-card class="stat-card">
          <mat-icon color="primary">check_circle</mat-icon>
          <div>
            <p class="stat-value">{{ activeCheckouts().length }}</p>
            <p class="stat-label">Active checkouts</p>
          </div>
        </mat-card>
        <mat-card class="stat-card overdue-card">
          <mat-icon color="warn">warning</mat-icon>
          <div>
            <p class="stat-value warn">{{ overdueCheckouts().length }}</p>
            <p class="stat-label">Overdue</p>
          </div>
        </mat-card>
        <mat-card class="stat-card">
          <mat-icon color="accent">bookmark</mat-icon>
          <div>
            <p class="stat-value">{{ pendingReservations().length }}</p>
            <p class="stat-label">Pending reservations</p>
          </div>
        </mat-card>
      </div>

      <!-- Overdue checkouts -->
      @if (overdueCheckouts().length) {
        <mat-card class="section-card">
          <mat-card-header>
            <mat-card-title>Overdue checkouts</mat-card-title>
          </mat-card-header>
          <mat-card-content>
            <table mat-table [dataSource]="overdueCheckouts()" class="full-width">
              <ng-container matColumnDef="member">
                <th mat-header-cell *matHeaderCellDef>Member</th>
                <td mat-cell *matCellDef="let c">{{ c.user.firstName }} {{ c.user.lastName }}</td>
              </ng-container>
              <ng-container matColumnDef="book">
                <th mat-header-cell *matHeaderCellDef>Book</th>
                <td mat-cell *matCellDef="let c">{{ c.book.title }}</td>
              </ng-container>
              <ng-container matColumnDef="due">
                <th mat-header-cell *matHeaderCellDef>Due date</th>
                <td mat-cell *matCellDef="let c">
                  <span class="overdue-date">{{ c.dueDate | date:'mediumDate' }}</span>
                </td>
              </ng-container>
              <ng-container matColumnDef="actions">
                <th mat-header-cell *matHeaderCellDef></th>
                <td mat-cell *matCellDef="let c">
                  <a mat-button [routerLink]="['/admin/checkouts']">Manage</a>
                </td>
              </ng-container>
              <tr mat-header-row *matHeaderRowDef="['member','book','due','actions']"></tr>
              <tr mat-row *matRowDef="let row; columns: ['member','book','due','actions']"></tr>
            </table>
          </mat-card-content>
        </mat-card>
      }

      <!-- Pending reservations ready to notify -->
      @if (pendingReservations().length) {
        <mat-card class="section-card">
          <mat-card-header>
            <mat-card-title>Pending reservations</mat-card-title>
          </mat-card-header>
          <mat-card-content>
            <table mat-table [dataSource]="pendingReservations()" class="full-width">
              <ng-container matColumnDef="member">
                <th mat-header-cell *matHeaderCellDef>Member</th>
                <td mat-cell *matCellDef="let r">{{ r.user.firstName }} {{ r.user.lastName }}</td>
              </ng-container>
              <ng-container matColumnDef="book">
                <th mat-header-cell *matHeaderCellDef>Book</th>
                <td mat-cell *matCellDef="let r">{{ r.book.title }}</td>
              </ng-container>
              <ng-container matColumnDef="since">
                <th mat-header-cell *matHeaderCellDef>Reserved</th>
                <td mat-cell *matCellDef="let r">{{ r.reservedAt | date:'mediumDate' }}</td>
              </ng-container>
              <ng-container matColumnDef="actions">
                <th mat-header-cell *matHeaderCellDef></th>
                <td mat-cell *matCellDef="let r">
                  <button mat-button color="primary" (click)="markReady(r)">Mark ready</button>
                </td>
              </ng-container>
              <tr mat-header-row *matHeaderRowDef="['member','book','since','actions']"></tr>
              <tr mat-row *matRowDef="let row; columns: ['member','book','since','actions']"></tr>
            </table>
          </mat-card-content>
        </mat-card>
      }

      <!-- Quick nav -->
      <div class="quick-nav">
        <a mat-raised-button routerLink="/admin/books"><mat-icon>library_books</mat-icon> Manage books</a>
        <a mat-raised-button routerLink="/admin/checkouts"><mat-icon>assignment_return</mat-icon> Manage checkouts</a>
        <a mat-raised-button routerLink="/admin/members"><mat-icon>people</mat-icon> Manage members</a>
      </div>
    </div>
  `,
  styles: [`
    .dashboard { padding: 24px; max-width: 1100px; margin: 0 auto; }
    .stats-row { display: flex; gap: 16px; margin-bottom: 24px; flex-wrap: wrap; }
    .stat-card { display: flex; gap: 16px; align-items: center; padding: 20px; flex: 1; min-width: 160px; }
    .stat-card mat-icon { font-size: 36px; width: 36px; height: 36px; }
    .stat-value { font-size: 28px; font-weight: 500; margin: 0; }
    .stat-label { font-size: 13px; color: #666; margin: 0; }
    .warn { color: #d32f2f; }
    .section-card { margin-bottom: 24px; }
    .full-width { width: 100%; }
    .overdue-date { color: #d32f2f; font-weight: 500; }
    .quick-nav { display: flex; gap: 12px; flex-wrap: wrap; margin-top: 8px; }
    .quick-nav a mat-icon { margin-right: 8px; }
  `]
})
export class AdminDashboardComponent implements OnInit {
  checkouts = signal<Checkout[]>([]);
  reservations = signal<Reservation[]>([]);

  activeCheckouts = () => this.checkouts().filter(c => !c.isReturned);
  overdueCheckouts = () => this.checkouts().filter(c =>
    !c.isReturned && new Date(c.dueDate) < new Date()
  );
  pendingReservations = () => this.reservations().filter(r => r.status === 'Pending');

  constructor(
    private checkoutsService: CheckoutsService,
    private reservationsService: ReservationsService
  ) {}

  ngOnInit() {
    this.checkoutsService.getAll().subscribe(c => this.checkouts.set(c));
    this.reservationsService.getAll().subscribe(r => this.reservations.set(r));
  }

  markReady(r: Reservation) {
    this.reservationsService.markReady(r.id).subscribe(() => {
      this.reservations.update(list =>
        list.map(x => x.id === r.id ? { ...x, status: 'Ready' as const } : x)
      );
    });
  }
}

// web/caclouky-react/src/pages/admin/AdminDashboard.tsx
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Alert, Box, Button, Card, CardContent, CircularProgress,
  Paper, Snackbar, Table, TableBody, TableCell, TableContainer,
  TableHead, TableRow, Typography
} from '@mui/material';
import { AssignmentReturn, EventNote, Warning } from '@mui/icons-material';
import type { Checkout, Reservation } from '../../types';
import * as api from '../../api';

export default function AdminDashboard() {
  const [checkouts, setCheckouts] = useState<Checkout[]>([]);
  const [reservations, setReservations] = useState<Reservation[]>([]);
  const [loading, setLoading] = useState(true);
  const [toast, setToast] = useState('');
  const navigate = useNavigate();

  useEffect(() => {
    Promise.all([api.getCheckouts(), api.getReservations()]).then(([c, r]) => {
      setCheckouts(c.data);
      setReservations(r.data);
    }).finally(() => setLoading(false));
  }, []);

  const overdue = checkouts.filter(c => !c.isReturned && new Date(c.dueDate) < new Date());
  const active = checkouts.filter(c => !c.isReturned);
  const pending = reservations.filter(r => r.status === 'Pending');

  const markReady = async (id: number) => {
    await api.readyReservation(id);
    setReservations(rs => rs.map(r => r.id === id ? { ...r, status: 'Ready' } : r));
    setToast('Marked as ready for pickup.');
  };

  if (loading) return <Box display="flex" justifyContent="center" py={8}><CircularProgress /></Box>;

  return (
    <Box p={3}>
      <Typography variant="h5" mb={3}>Dashboard</Typography>

      <Box display="flex" gap={2} mb={4} flexWrap="wrap">
        {[
          { label: 'Active Checkouts', value: active.length, icon: <AssignmentReturn /> },
          { label: 'Overdue', value: overdue.length, icon: <Warning />, warn: overdue.length > 0 },
          { label: 'Pending Reservations', value: pending.length, icon: <EventNote /> },
        ].map(stat => (
          <Card key={stat.label} sx={{ flex: 1, minWidth: 140 }}>
            <CardContent>
              <Box display="flex" alignItems="center" gap={1} color={stat.warn ? 'warning.main' : 'text.secondary'}>
                {stat.icon}
                <Typography variant="body2">{stat.label}</Typography>
              </Box>
              <Typography variant="h3" mt={1} color={stat.warn ? 'warning.main' : 'inherit'}>{stat.value}</Typography>
            </CardContent>
          </Card>
        ))}
      </Box>

      {overdue.length > 0 && (
        <Box mb={4}>
          <Typography variant="h6" mb={1}>Overdue Checkouts</Typography>
          <TableContainer component={Paper}>
            <Table size="small">
              <TableHead><TableRow>
                <TableCell>Member</TableCell><TableCell>Book</TableCell><TableCell>Due</TableCell>
              </TableRow></TableHead>
              <TableBody>
                {overdue.map(c => (
                  <TableRow key={c.id}>
                    <TableCell>{c.user.firstName} {c.user.lastName}</TableCell>
                    <TableCell>{c.book.title}</TableCell>
                    <TableCell sx={{ color: 'error.main' }}>{new Date(c.dueDate).toLocaleDateString()}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        </Box>
      )}

      {pending.length > 0 && (
        <Box mb={4}>
          <Typography variant="h6" mb={1}>Pending Reservations</Typography>
          <TableContainer component={Paper}>
            <Table size="small">
              <TableHead><TableRow>
                <TableCell>Member</TableCell><TableCell>Book</TableCell><TableCell>Reserved</TableCell><TableCell>Action</TableCell>
              </TableRow></TableHead>
              <TableBody>
                {pending.map(r => (
                  <TableRow key={r.id}>
                    <TableCell>{r.user.firstName} {r.user.lastName}</TableCell>
                    <TableCell>{r.book.title}</TableCell>
                    <TableCell>{new Date(r.reservedAt).toLocaleDateString()}</TableCell>
                    <TableCell><Button size="small" onClick={() => markReady(r.id)}>Mark Ready</Button></TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        </Box>
      )}

      <Box display="flex" gap={2} flexWrap="wrap">
        <Button variant="outlined" onClick={() => navigate('/admin/books')}>Manage Books</Button>
        <Button variant="outlined" onClick={() => navigate('/admin/checkouts')}>Manage Checkouts</Button>
        <Button variant="outlined" onClick={() => navigate('/admin/members')}>Manage Members</Button>
      </Box>

      <Snackbar open={!!toast} autoHideDuration={3000} onClose={() => setToast('')}>
        <Alert severity="success" onClose={() => setToast('')}>{toast}</Alert>
      </Snackbar>
    </Box>
  );
}
