// web/caclouky-web/src/app/features/admin/manage-checkouts/manage-checkouts.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { MatChipsModule } from '@angular/material/chips';
import { MatIconModule } from '@angular/material/icon';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatTabsModule } from '@angular/material/tabs';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../../environments/environment';

interface Checkout {
  id: number;
  checkedOutAt: string;
  dueDate: string;
  returnedAt?: string;
  isReturned: boolean;
  lateFee: number;
  book: { id: number; title: string; author: string };
  user: { id: string; firstName: string; lastName: string; email: string };
}

@Component({
  selector: 'app-manage-checkouts',
  standalone: true,
  imports: [
    CommonModule,
    MatTableModule, MatButtonModule, MatChipsModule,
    MatIconModule, MatSnackBarModule, MatProgressSpinnerModule, MatTabsModule
  ],
  template: `
    <div class="page">
      <h2>Checkouts</h2>

      @if (loading) {
        <mat-spinner diameter="40"></mat-spinner>
      } @else {
        <mat-tab-group>

          <mat-tab label="Active ({{ active.length }})">
            @if (active.length === 0) {
              <p class="empty">No active checkouts.</p>
            } @else {
              <table mat-table [dataSource]="active" class="mat-elevation-z2">
                <ng-container matColumnDef="member">
                  <th mat-header-cell *matHeaderCellDef>Member</th>
                  <td mat-cell *matCellDef="let c">
                    {{ c.user.firstName }} {{ c.user.lastName }}<br>
                    <span class="sub">{{ c.user.email }}</span>
                  </td>
                </ng-container>
                <ng-container matColumnDef="book">
                  <th mat-header-cell *matHeaderCellDef>Book</th>
                  <td mat-cell *matCellDef="let c"><strong>{{ c.book.title }}</strong></td>
                </ng-container>
                <ng-container matColumnDef="checkedOutAt">
                  <th mat-header-cell *matHeaderCellDef>Checked Out</th>
                  <td mat-cell *matCellDef="let c">{{ c.checkedOutAt | date:'mediumDate' }}</td>
                </ng-container>
                <ng-container matColumnDef="dueDate">
                  <th mat-header-cell *matHeaderCellDef>Due</th>
                  <td mat-cell *matCellDef="let c">
                    <span [class.overdue]="isOverdue(c.dueDate)">{{ c.dueDate | date:'mediumDate' }}</span>
                  </td>
                </ng-container>
                <ng-container matColumnDef="actions">
                  <th mat-header-cell *matHeaderCellDef></th>
                  <td mat-cell *matCellDef="let c">
                    <button mat-raised-button color="accent" (click)="returnBook(c)">
                      <mat-icon>assignment_return</mat-icon> Return
                    </button>
                  </td>
                </ng-container>
                <tr mat-header-row *matHeaderRowDef="activeCols"></tr>
                <tr mat-row *matRowDef="let row; columns: activeCols;"></tr>
              </table>
            }
          </mat-tab>

          <mat-tab label="History">
            @if (returned.length === 0) {
              <p class="empty">No returned checkouts.</p>
            } @else {
              <table mat-table [dataSource]="returned" class="mat-elevation-z2">
                <ng-container matColumnDef="member">
                  <th mat-header-cell *matHeaderCellDef>Member</th>
                  <td mat-cell *matCellDef="let c">{{ c.user.firstName }} {{ c.user.lastName }}</td>
                </ng-container>
                <ng-container matColumnDef="book">
                  <th mat-header-cell *matHeaderCellDef>Book</th>
                  <td mat-cell *matCellDef="let c"><strong>{{ c.book.title }}</strong></td>
                </ng-container>
                <ng-container matColumnDef="checkedOutAt">
                  <th mat-header-cell *matHeaderCellDef>Checked Out</th>
                  <td mat-cell *matCellDef="let c">{{ c.checkedOutAt | date:'mediumDate' }}</td>
                </ng-container>
                <ng-container matColumnDef="returnedAt">
                  <th mat-header-cell *matHeaderCellDef>Returned</th>
                  <td mat-cell *matCellDef="let c">{{ c.returnedAt | date:'mediumDate' }}</td>
                </ng-container>
                <ng-container matColumnDef="lateFee">
                  <th mat-header-cell *matHeaderCellDef>Late Fee</th>
                  <td mat-cell *matCellDef="let c">
                    {{ c.lateFee > 0 ? (c.lateFee | currency) : '—' }}
                  </td>
                </ng-container>
                <tr mat-header-row *matHeaderRowDef="historyCols"></tr>
                <tr mat-row *matRowDef="let row; columns: historyCols;"></tr>
              </table>
            }
          </mat-tab>

        </mat-tab-group>
      }
    </div>
  `,
  styles: [`
    .page { padding: 24px; }
    h2 { margin-bottom: 16px; }
    .empty { color: #888; padding: 24px 0; }
    table { width: 100%; margin-top: 16px; }
    .sub { font-size: 12px; color: #888; }
    .overdue { color: #c62828; font-weight: 500; }
  `]
})
export class ManageCheckoutsComponent implements OnInit {
  loading = true;
  active: Checkout[] = [];
  returned: Checkout[] = [];
  activeCols = ['member', 'book', 'checkedOutAt', 'dueDate', 'actions'];
  historyCols = ['member', 'book', 'checkedOutAt', 'returnedAt', 'lateFee'];

  constructor(private http: HttpClient, private snack: MatSnackBar) {}

  ngOnInit() { this.load(); }

  load() {
    this.loading = true;
    this.http.get<Checkout[]>(`${environment.apiUrl}/checkouts`).subscribe({
      next: all => {
        this.active = all.filter(c => !c.isReturned);
        this.returned = all.filter(c => c.isReturned);
        this.loading = false;
      },
      error: () => this.loading = false
    });
  }

  isOverdue(dueDate: string): boolean {
    return new Date(dueDate) < new Date();
  }

  returnBook(c: Checkout) {
    this.http.put<{ returnedAt: string; lateFee: number }>(
      `${environment.apiUrl}/checkouts/${c.id}/return`, {}
    ).subscribe({
      next: (res) => {
        const msg = res.lateFee > 0 ? `Returned. Late fee: $${res.lateFee.toFixed(2)}` : 'Book returned successfully.';
        this.snack.open(msg, 'Close', { duration: 4000 });
        this.load();
      },
      error: (err) => this.snack.open(err.error?.message ?? 'Return failed.', 'Close', { duration: 4000 })
    });
  }
}

<p>manage-checkouts works!</p>

// web/caclouky-react/src/pages/admin/ManageCheckouts.tsx
import { useEffect, useState } from 'react';
import {
  Alert, Box, Button, CircularProgress, Paper, Snackbar, Tab, Tabs,
  Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography
} from '@mui/material';
import type { Checkout } from '../../types';
import * as api from '../../api';

export default function ManageCheckouts() {
  const [checkouts, setCheckouts] = useState<Checkout[]>([]);
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState(0);
  const [toast, setToast] = useState<{ msg: string; severity: 'success' | 'error' } | null>(null);

  const load = () => {
    setLoading(true);
    api.getCheckouts().then(r => setCheckouts(r.data)).finally(() => setLoading(false));
  };
  useEffect(() => { load(); }, []);

  const active = checkouts.filter(c => !c.isReturned);
  const history = checkouts.filter(c => c.isReturned);
  const isOverdue = (c: Checkout) => !c.isReturned && new Date(c.dueDate) < new Date();

  const returnBook = async (c: Checkout) => {
    try {
      const res = await api.returnCheckout(c.id);
      const fee = (res.data as any).lateFee;
      setToast({ msg: fee > 0 ? `Returned. Late fee: $${fee.toFixed(2)}` : 'Book returned successfully.', severity: 'success' });
      load();
    } catch {
      setToast({ msg: 'Return failed.', severity: 'error' });
    }
  };

  if (loading) return <Box display="flex" justifyContent="center" py={8}><CircularProgress /></Box>;

  return (
    <Box p={3}>
      <Typography variant="h5" mb={2}>Manage Checkouts</Typography>
      <Tabs value={tab} onChange={(_, v) => setTab(v)} sx={{ mb: 2 }}>
        <Tab label={`Active (${active.length})`} />
        <Tab label={`History (${history.length})`} />
      </Tabs>

      {tab === 0 && (
        active.length === 0 ? <Typography color="text.secondary">No active checkouts.</Typography> : (
          <TableContainer component={Paper}>
            <Table size="small">
              <TableHead><TableRow>
                <TableCell>Member</TableCell><TableCell>Book</TableCell>
                <TableCell>Checked Out</TableCell><TableCell>Due Date</TableCell><TableCell>Action</TableCell>
              </TableRow></TableHead>
              <TableBody>
                {active.map(c => (
                  <TableRow key={c.id}>
                    <TableCell>{c.user.firstName} {c.user.lastName}</TableCell>
                    <TableCell>{c.book.title}</TableCell>
                    <TableCell>{new Date(c.checkedOutAt).toLocaleDateString()}</TableCell>
                    <TableCell sx={isOverdue(c) ? { color: 'error.main', fontWeight: 'bold' } : {}}>
                      {new Date(c.dueDate).toLocaleDateString()}
                    </TableCell>
                    <TableCell><Button size="small" variant="outlined" onClick={() => returnBook(c)}>Return</Button></TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        )
      )}

      {tab === 1 && (
        history.length === 0 ? <Typography color="text.secondary">No returned checkouts.</Typography> : (
          <TableContainer component={Paper}>
            <Table size="small">
              <TableHead><TableRow>
                <TableCell>Member</TableCell><TableCell>Book</TableCell>
                <TableCell>Checked Out</TableCell><TableCell>Returned</TableCell><TableCell>Late Fee</TableCell>
              </TableRow></TableHead>
              <TableBody>
                {history.map(c => (
                  <TableRow key={c.id}>
                    <TableCell>{c.user.firstName} {c.user.lastName}</TableCell>
                    <TableCell>{c.book.title}</TableCell>
                    <TableCell>{new Date(c.checkedOutAt).toLocaleDateString()}</TableCell>
                    <TableCell>{c.returnedAt ? new Date(c.returnedAt).toLocaleDateString() : '—'}</TableCell>
                    <TableCell>{c.lateFee ? `$${c.lateFee.toFixed(2)}` : '—'}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        )
      )}

      <Snackbar open={!!toast} autoHideDuration={4000} onClose={() => setToast(null)}>
        <Alert severity={toast?.severity} onClose={() => setToast(null)}>{toast?.msg}</Alert>
      </Snackbar>
    </Box>
  );
}
