// web/caclouky-web/src/app/features/catalog/book-detail/book-detail.component.ts
import { Component, OnInit, input, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatChipsModule } from '@angular/material/chips';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatIconModule } from '@angular/material/icon';
import { MatDividerModule } from '@angular/material/divider';
import { BooksService, Book } from '../../../core/services/books.service';
import { ReservationsService } from '../../../core/services/reservations.service';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-book-detail',
  standalone: true,
  imports: [
    CommonModule, RouterLink,
    MatButtonModule, MatChipsModule, MatSnackBarModule,
    MatProgressSpinnerModule, MatIconModule, MatDividerModule
  ],
  template: `
    <div class="detail-container">
      @if (loading()) {
        <mat-spinner diameter="48"></mat-spinner>
      } @else if (book()) {
        <a mat-button routerLink="/catalog">
          <mat-icon>arrow_back</mat-icon> Back to catalog
        </a>

        <div class="book-layout">
          <div class="cover">
            @if (book()!.coverImageUrl) {
              <img [src]="book()!.coverImageUrl" [alt]="book()!.title">
            } @else {
              <div class="cover-placeholder"><mat-icon>menu_book</mat-icon></div>
            }
          </div>

          <div class="info">
            <h1>{{ book()!.title }}</h1>
            <p class="author">by {{ book()!.author }}</p>

            <div class="meta">
              @if (book()!.genre) { <mat-chip>{{ book()!.genre }}</mat-chip> }
              @if (book()!.publishedYear) { <span class="year">{{ book()!.publishedYear }}</span> }
            </div>

            <mat-divider></mat-divider>

            <div class="copies">
              <span class="copies-label">Availability:</span>
              <span [class.available]="book()!.availableCopies > 0"
                    [class.unavailable]="book()!.availableCopies === 0">
                {{ book()!.availableCopies }} of {{ book()!.totalCopies }} copies available
              </span>
            </div>

            @if (book()!.isbn) {
              <p class="isbn">ISBN: {{ book()!.isbn }}</p>
            }
            @if (book()!.publisher) {
              <p class="publisher">Publisher: {{ book()!.publisher }}</p>
            }
            @if (book()!.description) {
              <p class="description">{{ book()!.description }}</p>
            }

            <div class="actions">
              @if (!auth.isLoggedIn()) {
                <a mat-raised-button color="primary" routerLink="/login">
                  Log in to reserve
                </a>
              } @else if (book()!.availableCopies === 0) {
                <button mat-raised-button color="accent"
                        [disabled]="reserving()"
                        (click)="reserve()">
                  {{ reserving() ? 'Reserving…' : 'Reserve (join waitlist)' }}
                </button>
              } @else {
                <button mat-raised-button color="accent"
                        [disabled]="reserving()"
                        (click)="reserve()">
                  {{ reserving() ? 'Reserving…' : 'Reserve' }}
                </button>
              }
            </div>
          </div>
        </div>
      }
    </div>
  `,
  styles: [`
    .detail-container { padding: 24px; max-width: 900px; margin: 0 auto; }
    .book-layout { display: flex; gap: 40px; margin-top: 16px; flex-wrap: wrap; }
    .cover { width: 220px; flex-shrink: 0; }
    .cover img { width: 100%; border-radius: 6px; box-shadow: 0 2px 12px rgba(0,0,0,.2); }
    .cover-placeholder { width: 220px; height: 300px; background: #f0f0f0; display: flex; align-items: center; justify-content: center; border-radius: 6px; }
    .cover-placeholder mat-icon { font-size: 80px; width: 80px; height: 80px; color: #ccc; }
    .info { flex: 1; }
    h1 { margin: 0 0 8px; font-size: 28px; }
    .author { font-size: 18px; color: #555; margin: 0 0 16px; }
    .meta { display: flex; gap: 12px; align-items: center; margin-bottom: 16px; flex-wrap: wrap; }
    .year { color: #888; font-size: 14px; }
    mat-divider { margin: 16px 0; }
    .copies { margin: 12px 0; font-size: 15px; }
    .copies-label { font-weight: 500; margin-right: 8px; }
    .available { color: #388e3c; font-weight: 500; }
    .unavailable { color: #d32f2f; font-weight: 500; }
    .isbn, .publisher { color: #666; font-size: 13px; margin: 4px 0; }
    .description { margin-top: 16px; line-height: 1.7; color: #444; }
    .actions { margin-top: 24px; }
  `]
})
export class BookDetailComponent implements OnInit {
  id = input.required<string>();
  book = signal<Book | null>(null);
  loading = signal(true);
  reserving = signal(false);

  constructor(
    private books: BooksService,
    public auth: AuthService,
    private reservations: ReservationsService,
    private snack: MatSnackBar
  ) {}

  ngOnInit() {
    this.books.getById(Number(this.id())).subscribe({
      next: b => { this.book.set(b); this.loading.set(false); },
      error: () => this.loading.set(false)
    });
  }

  reserve() {
    this.reserving.set(true);
    this.reservations.create(Number(this.id())).subscribe({
      next: () => {
        this.snack.open('Reservation placed successfully!', 'Close', { duration: 3000 });
        this.reserving.set(false);
      },
      error: (err) => {
        this.snack.open(err.error?.message ?? 'Could not reserve. Please try again.', 'Close', { duration: 4000 });
        this.reserving.set(false);
      }
    });
  }
}

// web/caclouky-react/src/pages/catalog/BookDetail.tsx
import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  Alert, Box, Button, Chip, CircularProgress, Divider, Snackbar, Typography
} from '@mui/material';
import { ArrowBack, LocalLibrary } from '@mui/icons-material';
import type { Book } from '../../types';
import * as api from '../../api';
import { useAuth } from '../../auth/AuthContext';

export default function BookDetail() {
  const { id } = useParams<{ id: string }>();
  const [book, setBook] = useState<Book | null>(null);
  const [loading, setLoading] = useState(true);
  const [reserving, setReserving] = useState(false);
  const [toast, setToast] = useState<{ msg: string; severity: 'success' | 'error' } | null>(null);
  const auth = useAuth();
  const navigate = useNavigate();

  useEffect(() => {
    if (!id) return;
    api.getBook(Number(id)).then(r => setBook(r.data)).finally(() => setLoading(false));
  }, [id]);

  const reserve = async () => {
    if (!book) return;
    setReserving(true);
    try {
      await api.createReservation(book.id);
      setToast({ msg: 'Reservation placed successfully!', severity: 'success' });
    } catch (err: any) {
      setToast({ msg: err.response?.data?.message ?? 'Could not reserve book.', severity: 'error' });
    } finally {
      setReserving(false);
    }
  };

  if (loading) return <Box display="flex" justifyContent="center" py={8}><CircularProgress /></Box>;
  if (!book) return <Typography p={4}>Book not found.</Typography>;

  return (
    <Box p={4} maxWidth={800} mx="auto">
      <Button startIcon={<ArrowBack />} onClick={() => navigate('/catalog')} sx={{ mb: 3 }}>Back</Button>
      <Box display="flex" gap={4} flexWrap="wrap">
        <Box flexShrink={0}>
          {book.coverImageUrl ? (
            <Box component="img" src={book.coverImageUrl} alt={book.title} sx={{ width: 220, borderRadius: 1, boxShadow: 3 }} />
          ) : (
            <Box width={220} height={300} display="flex" alignItems="center" justifyContent="center" bgcolor="grey.100" borderRadius={1}>
              <LocalLibrary sx={{ fontSize: 80, color: 'grey.400' }} />
            </Box>
          )}
        </Box>
        <Box flex={1} minWidth={200}>
          <Typography variant="h4" fontWeight="bold">{book.title}</Typography>
          <Typography variant="h6" color="text.secondary" mb={2}>by {book.author}</Typography>
          <Box display="flex" gap={1} mb={2} flexWrap="wrap">
            {book.genre && <Chip label={book.genre} />}
            {book.publishedYear && <Chip label={String(book.publishedYear)} variant="outlined" />}
            {book.isRestricted && <Chip label="Ministers Only" color="warning" />}
          </Box>
          <Divider sx={{ my: 2 }} />
          <Typography color={book.availableCopies > 0 ? 'success.main' : 'error.main'} fontWeight="bold" mb={1}>
            {book.availableCopies} of {book.totalCopies} copies available
          </Typography>
          {book.isbn && <Typography variant="body2" mb={0.5}>ISBN: {book.isbn}</Typography>}
          {book.publisher && <Typography variant="body2" mb={0.5}>Publisher: {book.publisher}</Typography>}
          {book.description && <Typography variant="body2" mt={2}>{book.description}</Typography>}
          <Box mt={3}>
            {!auth.isLoggedIn() ? (
              <Button variant="outlined" onClick={() => navigate('/login')}>Log in to reserve</Button>
            ) : (
              <Button variant="contained" onClick={reserve} disabled={reserving}>
                {reserving ? <><CircularProgress size={20} sx={{ mr: 1 }} />Reserving…</> :
                  book.availableCopies === 0 ? 'Reserve (join waitlist)' : 'Reserve'}
              </Button>
            )}
          </Box>
        </Box>
      </Box>
      <Snackbar open={!!toast} autoHideDuration={4000} onClose={() => setToast(null)}>
        <Alert severity={toast?.severity} onClose={() => setToast(null)}>{toast?.msg}</Alert>
      </Snackbar>
    </Box>
  );
}
